helm:
  parameters:
  - name: containerSpec.image
    value: us-docker.pkg.dev/phrasal-planet-437502-r5/oms/oms-frontend
    forcestring: true
  - name: containerSpec.tag
    value: v1.0.8
    forcestring: true
